"use client";

import type { CSSProperties, ReactNode } from "react";
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bell,
  Bot,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleDashed,
  CircleDot,
  Clock,
  Compass,
  Download,
  Ellipsis,
  History,
  Image as ImageIcon,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  Megaphone,
  MessagesSquare,
  Palette,
  Paperclip,
  Pause,
  PenLine,
  Plug,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Settings2,
  Shapes,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Target,
  Trash2,
  Upload,
  Users,
  UsersRound,
  X,
  Zap,
} from "lucide-react";

type IconProps = {
  name: string;
  size?: number;
  style?: CSSProperties;
  className?: string;
};

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "bar-chart-3": BarChart3,
  bell: Bell,
  bot: Bot,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  circle: Circle,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  clock: Clock,
  compass: Compass,
  download: Download,
  ellipsis: Ellipsis,
  history: History,
  image: ImageIcon,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "life-buoy": LifeBuoy,
  list: List,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "log-out": LogOut,
  mail: Mail,
  megaphone: Megaphone,
  "messages-square": MessagesSquare,
  palette: Palette,
  paperclip: Paperclip,
  pause: Pause,
  "pen-line": PenLine,
  plug: Plug,
  plus: Plus,
  "refresh-cw": RefreshCw,
  search: Search,
  settings: Settings,
  "settings-2": Settings2,
  shapes: Shapes,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  "trash-2": Trash2,
  "triangle-alert": AlertTriangle,
  upload: Upload,
  users: Users,
  "users-round": UsersRound,
  x: X,
  zap: Zap,
};

export function Icon({ name, size = 17, style, className }: IconProps): ReactNode {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} style={style} className={className} />;
}
